export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';

export const MAGNIFY_CARD = 'MAGNIFY_CARD';
export const MINIFY_CARD = 'MINIFY_CARD';
